# Generated by Django 3.0.2 on 2020-01-25 11:50

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('line1', models.CharField(max_length=250)),
                ('line2', models.CharField(blank=True, max_length=250, null=True)),
                ('apartment', models.CharField(blank=True, max_length=250, null=True)),
                ('building', models.CharField(blank=True, max_length=250, null=True)),
                ('landmark', models.CharField(blank=True, max_length=250, null=True)),
                ('district', models.CharField(default=None, max_length=250)),
                ('state', models.CharField(default=None, max_length=250)),
                ('pincode', models.CharField(default=None, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=250, verbose_name='coaching_branch_name')),
                ('branch_type', models.CharField(choices=[('Main', 'Main'), ('Sub', 'Sub')], default='Main', max_length=250, verbose_name='coaching_branch')),
            ],
        ),
        migrations.CreateModel(
            name='Coaching',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('logo_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('lat', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('region', models.IntegerField()),
                ('subregion', models.IntegerField()),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_of', to='webapi.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=250, verbose_name='branch_course_name')),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='')),
                ('fees', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('currency', models.CharField(blank=True, default='INR', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('stream', models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('Music', 'Music'), ('Dance', 'Dance')], default=None, max_length=250, verbose_name='coaching_stream')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_of', to='webapi.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='CoachingReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rating', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('coaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_of', to='webapi.Coaching')),
            ],
        ),
        migrations.CreateModel(
            name='CoachingMetaData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('contact', phone_field.models.PhoneField(default=None, help_text='coaching phone number', max_length=31)),
                ('help_contact', phone_field.models.PhoneField(blank=True, default=None, help_text='coaching phone number', max_length=31)),
                ('owner_name', models.CharField(blank=True, max_length=250, null=True)),
                ('owner_description', models.TextField(blank=True, null=True)),
                ('owner_image', models.ImageField(blank=True, null=True, upload_to='owners/')),
                ('owner_image_link', models.URLField(blank=True, default=None, null=True)),
                ('established_on', models.DateField()),
                ('coaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_of', to='webapi.Coaching')),
            ],
        ),
        migrations.CreateModel(
            name='CoachingFacultyMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('age', models.PositiveIntegerField()),
                ('specialization', models.CharField(max_length=250)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('faculty_image', models.ImageField(blank=True, null=True, upload_to='faculties/')),
                ('faculty_image_link', models.URLField()),
                ('coaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_of', to='webapi.Coaching')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='coaching',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='webapi.Coaching'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=250, verbose_name='course_batch_name')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('student_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('students_enrolled', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches_of', to='webapi.Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaches', to='webapi.CoachingFacultyMember')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_of', to='webapi.Branch'),
        ),
    ]
