# Generated by Django 3.0.2 on 2020-02-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocation',
            name='region',
        ),
        migrations.RemoveField(
            model_name='geolocation',
            name='subregion',
        ),
    ]
